### ISSUE TITLE
Docs are needed

### ISSUE THREAD

**Issue by willGraham01** [UCL-COMP0233-24-25/assignment-submission-checker#4]
We should have developer docs beyond just docstrings.

Ideally:

- [x] A docs build to be deployed on github pages #6 
- [x] A template for a bug report #9 
- [x] A template for a pull request #9
